spring:
  profiles:
    active: dev # 기본 활성 프로필
    group:
      dev: "dev"
      prod: "prod"
      test: "test"
  output:
    ansi:
      enabled: always

  application:
    name: omos

  # 서블릿 인코딩 설정
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#깃허브 토큰
github:
  token: ${GITHUB_TOKEN}